//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Data.Abstract
{
  public interface IAttachType
  {
  	int AttachTypeId { get; set; }
  
  	string AttachDescription { get; set; }
  
  	System.DateTime CreatedDate { get; set; }
  
  	int CreatedBy { get; set; }
  
  }
  public interface IBaseType
  {
  	short baseTypeId { get; set; }
  
  	string enumeration { get; set; }
  
  }
  public interface IFormPart
  {
  	int formPartId { get; set; }
  
  	int formId { get; set; }
  
  	int partId { get; set; }
  
  	Nullable<short> order { get; set; }
  
  }
  public interface IForm
  {
  	int formId { get; set; }
  
  	string identifier { get; set; }
  
  	string title { get; set; }
  
  	Nullable<int> EnterpriseID { get; set; }
  
  }
  public interface IFormText
  {
  	int frmTextId { get; set; }
  
  	int formId { get; set; }
  
  	int EnterpriseID { get; set; }
  
  	short langId { get; set; }
  
  	string frmTitle { get; set; }
  
  }
  public interface IItem
  {
  	int itemId { get; set; }
  
  	string identifier { get; set; }
  
  	string title { get; set; }
  
  	string label { get; set; }
  
  	string prompt { get; set; }
  
  	string itemBody { get; set; }
  
  	short langId { get; set; }
  
  }
  public interface IItemsEnt
  {
  	int itemEntId { get; set; }
  
  	int ent_id { get; set; }
  
  	int itemId { get; set; }
  
  	string identifier { get; set; }
  
  	string title { get; set; }
  
  	string label { get; set; }
  
  	string prompt { get; set; }
  
  	string itemBody { get; set; }
  
  	short langId { get; set; }
  
  }
  public interface IItemText
  {
  	int itemTextId { get; set; }
  
  	int itemId { get; set; }
  
  	int EnterpriseID { get; set; }
  
  	short langId { get; set; }
  
  	string title { get; set; }
  
  	string label { get; set; }
  
  	string prompt { get; set; }
  
  	string itemBody { get; set; }
  
  }
  public interface IItemVariable
  {
  	int itemVariableId { get; set; }
  
  	int itemId { get; set; }
  
  	string identifier { get; set; }
  
  	short baseTypeId { get; set; }
  
  	string defaultValue { get; set; }
  
  	Nullable<int> outcomeDeclarationId { get; set; }
  
  }
  public interface ILanguage
  {
  	short langId { get; set; }
  
  	string languageRegion { get; set; }
  
  	string title { get; set; }
  
  }
  public interface ILookupDetail
  {
  	int lookupDetailId { get; set; }
  
  	int lookupMasterId { get; set; }
  
  	Nullable<int> EnterpriseID { get; set; }
  
  	Nullable<int> GroupID { get; set; }
  
  	int displayOrder { get; set; }
  
  	string dataValue { get; set; }
  
  	string StatusFlag { get; set; }
  
  }
  public interface ILookupMaster
  {
  	int lookupMasterId { get; set; }
  
  	string lookupCode { get; set; }
  
  	string title { get; set; }
  
  	short baseTypeId { get; set; }
  
  }
  public interface ILookupText
  {
  	int lookupTextId { get; set; }
  
  	int lookupDetailId { get; set; }
  
  	short langId { get; set; }
  
  	string displayText { get; set; }
  
  }
  public interface IPart
  {
  	int partId { get; set; }
  
  	string identifier { get; set; }
  
  	Nullable<int> branchRuleId { get; set; }
  
  	string title { get; set; }
  
  }
  public interface IPartSection
  {
  	int partSectionId { get; set; }
  
  	int partId { get; set; }
  
  	int sectionId { get; set; }
  
  	Nullable<short> order { get; set; }
  
  	Nullable<bool> visible { get; set; }
  
  }
  public interface IPartSectionsEnt
  {
  	int partSectionEntId { get; set; }
  
  	int partSectionId { get; set; }
  
  	int entPartSectionId { get; set; }
  
  	int EnterpriseID { get; set; }
  
  	bool visible { get; set; }
  
  }
  public interface IPartText
  {
  	int prtTextId { get; set; }
  
  	int partId { get; set; }
  
  	int EnterpriseID { get; set; }
  
  	short langId { get; set; }
  
  	string prtTitle { get; set; }
  
  }
  public interface ISectionItem
  {
  	int sectionItemId { get; set; }
  
  	int sectionId { get; set; }
  
  	int itemId { get; set; }
  
  	Nullable<int> subSectionId { get; set; }
  
  	Nullable<short> order { get; set; }
  
  	int validation { get; set; }
  
  	bool display { get; set; }
  
  	bool readOnly { get; set; }
  
  	bool requiredSection { get; set; }
  
  	bool requiredForm { get; set; }
  
  }
  public interface ISectionItemsEnt
  {
  	int sectionItemEntId { get; set; }
  
  	int sectionItemId { get; set; }
  
  	int validation { get; set; }
  
  	bool display { get; set; }
  
  	bool readOnly { get; set; }
  
  	bool requiredSection { get; set; }
  
  	bool requiredForm { get; set; }
  
  	int EnterpriseID { get; set; }
  
  }
  public interface ISection
  {
  	int sectionId { get; set; }
  
  	string identifier { get; set; }
  
  	string title { get; set; }
  
  	bool visible { get; set; }
  
  	string href { get; set; }
  
  	Nullable<int> branchRuleId { get; set; }
  
  	string rubricBlock { get; set; }
  
  	bool multipleItemsPerPage { get; set; }
  
  }
  public interface ISectionText
  {
  	int sctnTextId { get; set; }
  
  	int sectionId { get; set; }
  
  	int EnterpriseID { get; set; }
  
  	short langId { get; set; }
  
  	string sctnTitle { get; set; }
  
  }
  public interface ISubSection
  {
  	int subSectionId { get; set; }
  
  	int sectionId { get; set; }
  
  }
}
